<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Responsive carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Responsive carousel" />
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="../slide_header_droite/engine2/style.css" />
	<script type="text/javascript" src="../slide_header_droite/engine2/jquery.js"></script>

	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#f0f0f0;margin:auto">
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container2">
	<div class="ws_images"><ul>
<li><img src="data2/images/rodeo4.jpg" alt="rodeo1-174d75b18e" title="rodeo1-174d75b18e" id="wows2_0"/></li>
<li><img src="data2/images/rodeo2.jpg" alt="rodeo2-0098495109" title="rodeo2-0098495109" id="wows2_1"/></li>
<li><img src="data2/images/rodeo1.jpg" alt="rodeo4-b63e355c6a" title="rodeo4-b63e355c6a" id="wows2_2"/></li>
<li><img src="data2/images/rodeo3.jpg" alt="rodeo5-410812a970" title="rodeo5-410812a970" id="wows2_3"/></li>
<li><a href="#"><img src="data2/images/rodeo5.jpg" alt="full screen slider" title="rodeo6-8f56d77afe (1)" id="wows2_4"/></a></li>
<li><img src="data2/images/rodeo6.jpg" alt="rodeo6-8f56d77afe" title="rodeo6-8f56d77afe" id="wows2_5"/></li>
</ul></div>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="../slide_header_droite/engine2/wowslider.js"></script>
	<script type="text/javascript" src="../slide_header_droite/engine2/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>