<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Responsive carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Responsive carousel" />
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="../slide_footer/engine1/style.css" />
	<script type="text/javascript" src="../slide_footer/engine1/jquery.js"></script>

	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7;margin:auto">
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="../slide_footer/data1/images/rodeo1.png" alt="company_logos_01_rodeo" title="company_logos_01_rodeo" id="wows1_0"/></li>
<li><img src="../slide_footer/data1/images/rodeo2.png" alt="company_logos_01_rodeo" title="company_logos_01_rodeo" id="wows1_1"/></li>
<li><img src="../slide_footer/data1/images/rodeo3.png" alt="company_logos_01_rodeo" title="company_logos_01_rodeo" id="wows1_2"/></li>
</ul></div>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="../slide_footer/engine1/wowslider.js"></script>
	<script type="text/javascript" src="../slide_footer/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>